### ISSUE TITLE
Reference Error: Element is not defined while using Nuxt

### ISSUE THREAD

**Issue by JefferySJones** [guanzo/vue-smooth-reflow#10]
ReferenceError: Element is not defined at Module.<anonymous> (/node_modules/vue-smooth-reflow/dist/vue-smooth-reflow.min.js:1:9103)

**Comment by guanzo** [comment]
Sorry about that, will fix it ASAP.

**Comment by JefferySJones** [comment]
It looks like this fixes the issue: https://github.com/JefferySJones/vue-smooth-reflow/commit/4aa141b49caae56e2536bad7b120430fb660169c

**Comment by guanzo** [comment]
Awesome, would you like to make it a pull request?

**Comment by guanzo** [comment]
I've confirmed that your fix works in nuxt, and have published the fix to npm. Thanks for your contribution.
