### ISSUE TITLE
problem with msMatchesSelector

### ISSUE THREAD

**Issue by R1ze13** [guanzo/vue-smooth-reflow#12]
Hey! First of all thx for the awesome plugin

But i got a problem with this method https://github.com/guanzo/vue-smooth-reflow/blob/master/src/index.js#L12
In some browsers i got error "t.msMatchesSelector is not a function" (unfortunately i don't know which ones) so i suggest to use this polyfill https://paste.ofcode.org/CfPD6ssEYybycWANiC3yfE

**Comment by guanzo** [comment]
Hmm okay, thanks for the report. I'll spend some time finding the best polyfill.

**Comment by guanzo** [comment]
Published the polyfill with version 0.1.12, thanks!
