### ISSUE TITLE
Uable to use vue-smooth-reflow due to ES7 Spread Operator.

### ISSUE THREAD

**Issue by MichMich** [guanzo/vue-smooth-reflow#2]
Due to the ES7 Spread Operator on line 106 im unable to import the vue-smooth-reflow library.

> ERROR in ./node_modules/vue-smooth-reflow/src/index.js
> Module parse failed: Unexpected token (106:12)
> You may need an appropriate loader to handle this file type.
> |             hideOverflow: true,
> |             debug: false,
> |             ...userOptions
> |         }
> |         let properties = this.parsePropertyOption(options.property)

Is there a way to solve this?

Cheers, Michael

**Comment by guanzo** [comment]
Yes, this should be solved on my end. Are you using a module bundle, and could you post its configuration?

**Comment by MichMich** [comment]
It seems to be fixed in this commit: https://github.com/guanzo/vue-smooth-reflow/commit/c123673ea7b3f2b7fc6b88449a46c22f9911627b

Thanks.

**Comment by guanzo** [comment]
Great!
